/**
 * Noesis.io Health  - EDI Clearinghouse Service
 * © 2026 Athena Core Technologies, Inc.
 *
 * Handles EDI 837P/837I claim submission and 835 ERA parsing.
 * Designed to connect to any X12-compliant clearinghouse:
 *   - Office Ally   (free for small practices, recommended entry point)
 *   - Change Healthcare / Optum
 *   - Availity
 *   - Waystar / Relay Health
 *
 * Environment variables:
 *   CLEARINGHOUSE_PROVIDER   = 'office_ally' | 'change_healthcare' | 'availity'
 *   CLEARINGHOUSE_API_URL    = base URL for the clearinghouse REST API
 *   CLEARINGHOUSE_API_KEY    = API key / client ID
 *   CLEARINGHOUSE_API_SECRET = API secret (if required)
 *   CLEARINGHOUSE_SENDER_ID  = your EDI sender ID / submitter NPI
 *
 * When not configured, all methods return realistic demo responses
 * so the UI and tests work without a live clearinghouse account.
 */

const https  = require('https');
const http   = require('http');
const crypto = require('crypto');
const { toCents } = require('../utils/money');

const PROVIDER   = process.env.CLEARINGHOUSE_PROVIDER   || 'demo';
const API_URL    = process.env.CLEARINGHOUSE_API_URL    || '';
const API_KEY    = process.env.CLEARINGHOUSE_API_KEY    || '';
const API_SECRET = process.env.CLEARINGHOUSE_API_SECRET || '';
const SENDER_ID  = process.env.CLEARINGHOUSE_SENDER_ID  || 'NOESIS01';

function isConfigured() {
  return !!(API_URL && API_KEY && PROVIDER !== 'demo');
}

function getStatus() {
  return {
    provider:    PROVIDER,
    configured:  isConfigured(),
    apiUrl:      API_URL || null,
    senderId:    SENDER_ID,
    formats:     ['EDI X12 837P', 'EDI X12 837I', 'EDI X12 835', 'EDI X12 270/271'],
    features:    ['claim_submission', 'era_retrieval', 'eligibility_270', 'claim_status_276'],
    clearinghouses: [
      { name: 'Office Ally',        id: 'office_ally',        free: true,  notes: 'Free for practices, requires enrollment' },
      { name: 'Change Healthcare',  id: 'change_healthcare',  free: false, notes: 'Enterprise-grade, largest payer network' },
      { name: 'Availity',           id: 'availity',           free: false, notes: 'Strong payer-direct connections' },
      { name: 'Waystar',            id: 'waystar',            free: false, notes: 'Good denial management workflow' },
    ],
  };
}

// ── EDI 837P Segment Builder ─────────────────────────────────────────────────

function buildISASegment(senderId, receiverId, date, time, controlNum) {
  const d = date || new Date();
  const dateStr = d.toISOString().slice(2, 10).replace(/-/g, '');
  const timeStr = d.toISOString().slice(11, 16).replace(':', '');
  const ctrl    = String(controlNum || Math.floor(Math.random() * 999999999)).padStart(9, '0');
  return [
    'ISA', '00', '          ', '00', '          ',
    'ZZ', senderId.padEnd(15), 'ZZ', receiverId.padEnd(15),
    dateStr, timeStr, '^', '00501', ctrl, '0', 'P', ':',
  ].join('*') + '~';
}

function buildGSSegment(senderId, receiverId, date, groupCtrl) {
  const d = date || new Date();
  const dateStr = d.toISOString().slice(0, 10).replace(/-/g, '');
  const timeStr = d.toISOString().slice(11, 16).replace(':', '');
  return ['GS', 'HC', senderId, receiverId, dateStr, timeStr, groupCtrl || '1', 'X', '005010X222A1'].join('*') + '~';
}

/**
 * Build a minimal EDI 837P (Professional) claim.
 * In production this is generated by a full EDI library (node-x12, etc.).
 * This scaffold produces a structurally valid 837P for testing.
 */
function build837P(claim, provider, payer) {
  const now        = new Date();
  const controlNum = Math.floor(Math.random() * 999999999);
  const lines      = [];

  lines.push(buildISASegment(SENDER_ID, payer.ediId || 'PAYERID00000001', now, now, controlNum));
  lines.push(buildGSSegment(SENDER_ID, payer.ediId || 'PAYERID00000001', now, 1));
  lines.push('ST*837*0001*005010X222A1~');
  lines.push(`BPR*22*${(claim.amount || 0).toFixed(2)}*C*ACH*CCP*01*${payer.bankRoutingNumber || '021000021'}*DA*${payer.bankAccountNumber || '00000001'}*1512345678**01*${provider.bankRoutingNumber || '021000021'}*DA*${provider.bankAccountNumber || '00000002'}*${now.toISOString().slice(0, 10).replace(/-/g, '')}~`);
  lines.push(`NM1*41*2*${(provider.organizationName || 'PROVIDER PRACTICE').toUpperCase()}*****46*${provider.npi || '0000000000'}~`);
  lines.push(`PER*IC*BILLING*TE*${provider.phone || '5555555555'}~`);
  lines.push(`NM1*40*2*${(payer.name || 'INSURANCE PAYER').toUpperCase()}*****46*${payer.payerId || 'PAYERID'}~`);
  lines.push('HL*1**20*1~');
  lines.push(`NM1*85*2*${(provider.organizationName || 'PROVIDER PRACTICE').toUpperCase()}*****XX*${provider.npi || '0000000000'}~`);
  lines.push(`N3*${provider.address || '123 MEDICAL DR'}~`);
  lines.push(`N4*${provider.city || 'ANYTOWN'}*${provider.state || 'FL'}*${provider.zip || '00000'}~`);
  lines.push('HL*2*1*22*0~');
  lines.push(`NM1*IL*1*${(claim.patientLastName || 'DOE').toUpperCase()}*${(claim.patientFirstName || 'JOHN').toUpperCase()}****MI*${claim.memberId || 'MEM000001'}~`);
  lines.push(`N3*${claim.patientAddress || '456 PATIENT ST'}~`);
  lines.push(`N4*${claim.patientCity || 'ANYTOWN'}*${claim.patientState || 'FL'}*${claim.patientZip || '00000'}~`);
  lines.push(`DMG*D8*${(claim.patientDob || '19800101').replace(/-/g, '')}*${claim.patientGender === 'F' ? 'F' : 'M'}~`);
  lines.push(`CLM*${claim.id || 'CLM001'}*${(claim.amount || 0).toFixed(2)}***${claim.placeOfService || '11'}:B:1*Y*A*Y*I~`);
  lines.push(`DTP*472*D8*${(claim.serviceDate || now.toISOString().slice(0, 10)).replace(/-/g, '')}~`);
  lines.push(`HI*ABK:${claim.icd10Code || 'Z00.00'}~`);
  lines.push(`NM1*82*1*${(provider.lastName || 'PROVIDER').toUpperCase()}*${(provider.firstName || 'BILLING').toUpperCase()}****XX*${provider.npi || '0000000000'}~`);
  lines.push(`LX*1~`);
  lines.push(`SV1*HC:${claim.cptCode || '99213'}*${(claim.amount || 0).toFixed(2)}*UN*1*${claim.placeOfService || '11'}~`);
  lines.push(`DTP*472*D8*${(claim.serviceDate || now.toISOString().slice(0, 10)).replace(/-/g, '')}~`);
  lines.push('SE*22*0001~');
  lines.push('GE*1*1~');
  lines.push(`IEA*1*${String(controlNum).padStart(9, '0')}~`);

  return lines.join('\n');
}

/**
 * Parse an 835 ERA (Electronic Remittance Advice) into structured JSON.
 * Handles multi-claim ERAs with CARC/RARC codes.
 */
function parse835ERA(ediText) {
  if (!ediText || typeof ediText !== 'string') {
    return { success: false, error: 'No EDI text provided' };
  }

  const segments = ediText.split(/[~\n]/).map((s) => s.trim()).filter(Boolean);
  const result   = { payments: [], payer: {}, payee: {}, checkNumber: null, totalPaid: 0 };
  let currentClaim = null;

  for (const seg of segments) {
    const els = seg.split('*');
    const id  = els[0];

    if (id === 'N1' && els[1] === 'PR') { result.payer = { name: els[2], id: els[4] }; }
    if (id === 'N1' && els[1] === 'PE') { result.payee = { name: els[2], npi: els[4] }; }
    // 835 ERA reconciliation: amounts must equal payer-reported cents exactly,
    // so route every parse through Decimal-backed toCents() rather than parseFloat
    // which loses precision on values that compound (allowed * coinsurance).
    if (id === 'BPR')                   { result.totalPaid = toCents(els[2]); result.checkNumber = els[9]; }

    if (id === 'CLP') {
      if (currentClaim) { result.payments.push(currentClaim); }
      currentClaim = {
        claimId:       els[1],
        status:        els[2] === '1' ? 'paid' : els[2] === '2' ? 'adjusted' : els[2] === '3' ? 'denied' : 'other',
        claimAmount:   toCents(els[3]),
        paidAmount:    toCents(els[4]),
        patientLiability: toCents(els[5]),
        payerClaimId:  els[7],
        adjustments:   [],
        serviceLines:  [],
      };
    }

    if (id === 'CAS' && currentClaim) {
      currentClaim.adjustments.push({
        groupCode:   els[1],
        reasonCode:  els[2],
        amount:      toCents(els[3]),
        quantity:    toCents(els[4]),
      });
    }

    if (id === 'SVC' && currentClaim) {
      currentClaim.serviceLines.push({
        procedure:    els[1],
        submittedAmt: toCents(els[2]),
        paidAmt:      toCents(els[3]),
        revenueCode:  els[4],
      });
    }
  }

  if (currentClaim) { result.payments.push(currentClaim); }
  return { success: true, ...result };
}

// ── API Helpers ───────────────────────────────────────────────────────────────

function makeRequest(method, path, body, extraHeaders = {}) {
  return new Promise((resolve, reject) => {
    const urlObj  = new URL(API_URL + path);
    const isHttps = urlObj.protocol === 'https:';
    const lib     = isHttps ? https : http;

    const payload = body ? JSON.stringify(body) : null;
    const headers = {
      'Content-Type':  'application/json',
      'Authorization': `Bearer ${API_KEY}`,
      'X-Sender-ID':   SENDER_ID,
      ...extraHeaders,
    };
    if (payload) { headers['Content-Length'] = Buffer.byteLength(payload); }

    const options = {
      hostname: urlObj.hostname,
      port:     urlObj.port || (isHttps ? 443 : 80),
      path:     urlObj.pathname + urlObj.search,
      method,
      headers,
    };

    const req = lib.request(options, (res) => {
      let data = '';
      res.on('data', (c) => { data += c; });
      res.on('end', () => {
        try {
          resolve({ status: res.statusCode, body: JSON.parse(data) });
        } catch {
          resolve({ status: res.statusCode, body: data });
        }
      });
    });

    req.on('error', reject);
    if (payload) { req.write(payload); }
    req.end();
  });
}

// ── Public Methods ────────────────────────────────────────────────────────────

/**
 * Submit an 837P claim to the clearinghouse.
 * Returns a tracking ID and initial status.
 */
async function submitClaim(claim, provider, payer) {
  const edi837 = build837P(claim, provider, payer);
  const trackingId = `CLR-${Date.now()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;

  if (!isConfigured()) {
    return {
      success:     true,
      demo:        true,
      trackingId,
      status:      'accepted',
      statusCode:  'A',
      message:     'Claim accepted by clearinghouse (demo mode)',
      edi837,
      submittedAt: new Date().toISOString(),
      estimatedPaymentDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    };
  }

  try {
    const res = await makeRequest('POST', '/claims/submit', {
      format:    'EDI_837P',
      content:   edi837,
      claimId:   claim.id,
      senderId:  SENDER_ID,
    });

    return {
      success:     res.status < 300,
      trackingId:  res.body?.trackingId || trackingId,
      status:      res.body?.status     || 'pending',
      statusCode:  res.body?.statusCode || 'P',
      message:     res.body?.message    || 'Submitted',
      edi837,
      rawResponse: res.body,
      submittedAt: new Date().toISOString(),
    };
  } catch (err) {
    return { success: false, error: err.message, trackingId };
  }
}

/**
 * Check the status of a previously submitted claim (EDI 276).
 */
async function getClaimStatus(trackingId) {
  if (!isConfigured()) {
    const statuses = ['accepted', 'in_process', 'finalized_paid', 'finalized_denied'];
    return {
      success:    true,
      demo:       true,
      trackingId,
      status:     statuses[Math.floor(Date.now() / 10000) % statuses.length],
      lastUpdated: new Date().toISOString(),
    };
  }

  try {
    const res = await makeRequest('GET', `/claims/${trackingId}/status`);
    return { success: res.status < 300, trackingId, ...res.body };
  } catch (err) {
    return { success: false, error: err.message, trackingId };
  }
}

/**
 * Retrieve 835 ERA files from the clearinghouse.
 * Returns parsed payment data.
 */
async function getERAs({ fromDate, toDate, limit = 20 } = {}) {
  if (!isConfigured()) {
    return {
      success: true,
      demo:    true,
      eras: [{
        eraId:        'ERA-DEMO-001',
        checkNumber:  'CHK-00001',
        payerName:    'Aetna Health Plans',
        totalPaid:    4250.00,
        claimCount:   8,
        receivedAt:   new Date().toISOString(),
        payments: [
          { claimId: 'CLM-001', paidAmount: 720.00,  claimAmount: 850.00,  status: 'paid' },
          { claimId: 'CLM-002', paidAmount: 0,        claimAmount: 350.00,  status: 'denied', reasonCode: 'CO-18' },
          { claimId: 'CLM-003', paidAmount: 1100.00, claimAmount: 1200.00, status: 'adjusted', reasonCode: 'CO-45' },
        ],
      }],
    };
  }

  try {
    const params = new URLSearchParams({ limit });
    if (fromDate) { params.set('from', fromDate); }
    if (toDate)   { params.set('to', toDate); }
    const res = await makeRequest('GET', `/eras?${params.toString()}`);

    const eras = (res.body?.eras || []).map((era) => ({
      ...era,
      parsed: era.content ? parse835ERA(era.content) : null,
    }));

    return { success: res.status < 300, eras };
  } catch (err) {
    return { success: false, error: err.message, eras: [] };
  }
}

/**
 * Send EDI 270 eligibility request through the clearinghouse.
 * (Alternative to direct payer API  - same network, different path)
 */
async function checkEligibility270(patient, provider, payer) {
  if (!isConfigured()) {
    return {
      success:   true,
      demo:      true,
      eligible:  true,
      memberId:  patient.memberId || 'MEM-DEMO-001',
      planName:  'PPO Gold  - Demo Plan',
      deductible: { total: 1500, met: 420 },
      outOfPocket: { total: 4000, met: 840 },
      copays: { primaryCare: 30, specialist: 60, urgent: 90, emergency: 350 },
    };
  }

  try {
    const res = await makeRequest('POST', '/eligibility/270', { patient, provider, payer });
    return { success: res.status < 300, ...res.body };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

module.exports = {
  getStatus,
  isConfigured,
  submitClaim,
  getClaimStatus,
  getERAs,
  checkEligibility270,
  build837P,
  parse835ERA,
};
